language: php
php:
  - 7.3
os: linux
services:
  - docker
before_script:
  - cp .env.testing .env
  - composer install
script:
  - php artisan test --filter=FuncionesCompletasTest
  - php artisan test --filter=loginTest
  - php artisan test --filter=suprimirUsuarioTest
