version: '2'
services:
  app:
    restart: unless-stopped
    container_name: laravel_app
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html