# name: ci

# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       -
#         name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           push: true
#           tags: akuster/laravel-backoffice-actions
#       - name: Checkout repository
#         uses: actions/checkout@v2
        
#       - name: Set up Kubernetes CLI
#         uses: azure/k8s-set-context@v1
#         with:
#           kubeconfig: ${{ secrets.KUBECONFIG }}
        
#       - name: Verify Kubernetes connectivity
#         run: |
#           kubectl cluster-info
#           kubectl get pods --all-namespaces
  