name: Docker Image CI

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
      - name: Start the app containers
        run: docker-compose up -d
        working-directory: ./

      - name: Run the PHPUnit tests
        run: docker exec -ti laravel_app php artisan test --filter=GradoControllerTest
        working-directory: ./

      - name: Stop the app containers
        run: docker-compose down
        working-directory: ./
