name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, pdo_mysql

    - name: Copy .env file
      run: cp .env.example .env

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Create database
      run: |
        mysql -e 'create database if not exists test;'
        php artisan migrate --env=testing

    - name: Run tests
      run: php artisan test --filter=CarreraControllerTest
