name: Laravel Test

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: homestead
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, zip, pcntl
    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
    - name: Install Dependencies
      run: composer install
    - name: Start services
      run: docker-compose up -d
      working-directory: .
    - name: Wait for MySQL
      run: docker-compose exec -T mysql mysqladmin --user=homestead --password=secret --host "127.0.0.1" --port=3306 --silent --wait=30 ping
      working-directory: .
    - name: Generate key
      run: php artisan key:generate
      working-directory: .
    - name: Run tests
      run: php artisan test --filter=CarreraControllerTest
      working-directory: .
    - name: Stop services
      run: docker-compose down
      working-directory: .
