name: SSH Action

on: [push]

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Run SSH command
        run: |
          sshpass -p ${{ secrets.SERVER_PASSWORD }} \
          ssh -o StrictHostKeyChecking=no \
          -p 223 \
          username@${{ secrets.SERVER_IP }} kubectl set image deployment/laravel-app laravel-backoffice-kubernetes=akuster/laravel-backoffice-kubernetes:latest
