name: Test Kubernetes Connectivity

on:
  push:
    branches:
      - main

jobs:
  test_connectivity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Kubernetes CLI
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      
    - name: Verify Kubernetes connectivity
      run: |
        kubectl cluster-info
        kubectl get pods --all-namespaces